-- Criar schema dedicado para o projeto
CREATE SCHEMA IF NOT EXISTS inlab_payroll_tools;

-- Calculadoras cadastradas
CREATE TABLE IF NOT EXISTS inlab_payroll_tools.calculators (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL, -- 'ferias', 'prolabore', 'custo-funcionario', '13o'
  title TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Variantes e pesos para A/B (por calculator ou global)
CREATE TABLE IF NOT EXISTS inlab_payroll_tools.ab_variants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  calculator_slug TEXT NOT NULL REFERENCES inlab_payroll_tools.calculators(slug),
  variant TEXT NOT NULL,        -- ex: 'ferias', 'prolabore' etc. ou rótulos alternativos
  weight INT NOT NULL DEFAULT 1,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Eventos de tracking
CREATE TABLE IF NOT EXISTS inlab_payroll_tools.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT,
  user_id TEXT,               -- Clerk userId quando autenticado
  email TEXT,                 -- coletado antes do login
  calculator_slug TEXT,
  variant TEXT,
  event TEXT NOT NULL,        -- 'view','start','calculate','save_email','conversion'
  article_slug TEXT,
  referrer TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS events_created_at_idx ON inlab_payroll_tools.events (created_at);
CREATE INDEX IF NOT EXISTS events_calc_event_idx ON inlab_payroll_tools.events (calculator_slug, event);

-- Cálculos salvos
CREATE TABLE IF NOT EXISTS inlab_payroll_tools.calculations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id TEXT,
  user_id TEXT,
  email TEXT,
  calculator_slug TEXT NOT NULL,
  inputs JSONB NOT NULL,
  outputs JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Índices para cálculos
CREATE INDEX IF NOT EXISTS calculations_user_created_idx ON inlab_payroll_tools.calculations (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS calculations_email_idx ON inlab_payroll_tools.calculations (email);

-- Leads
CREATE TABLE IF NOT EXISTS inlab_payroll_tools.leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL DEFAULT 'unverified', -- 'unverified' | 'verified' | 'user_created'
  created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS desabilitado conforme requisitos (apenas para leitura pública)
ALTER TABLE inlab_payroll_tools.calculators DISABLE ROW LEVEL SECURITY;
ALTER TABLE inlab_payroll_tools.ab_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE inlab_payroll_tools.events DISABLE ROW LEVEL SECURITY;
ALTER TABLE inlab_payroll_tools.calculations DISABLE ROW LEVEL SECURITY;
ALTER TABLE inlab_payroll_tools.leads DISABLE ROW LEVEL SECURITY;

-- Inserir calculadoras iniciais
INSERT INTO inlab_payroll_tools.calculators (slug, title) VALUES
  ('ferias', 'Calculadora de Férias'),
  ('prolabore', 'Calculadora de Pró-Labore'),
  ('custo-funcionario', 'Calculadora de Custo do Funcionário'),
  ('13o-salario', 'Calculadora de 13º Salário')
ON CONFLICT (slug) DO NOTHING;

-- Inserir variantes A/B iniciais (pesos iguais)
INSERT INTO inlab_payroll_tools.ab_variants (calculator_slug, variant, weight) VALUES
  ('ferias', 'ferias', 1),
  ('prolabore', 'prolabore', 1),
  ('custo-funcionario', 'custo-funcionario', 1),
  ('13o-salario', '13o-salario', 1)
ON CONFLICT DO NOTHING;
